services:
  app:
    build: 
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5001:5001"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"
    # This line pulls in every variable from your .env file
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: